export const START_LOAD_USER = "START_LOAD_USER";
export const STOP_LOAD_USER = "STOP_LOAD_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";