export const START_LOADING_POSTS = "START_LOADING_POSTS";
export const STOP_LOADING_POSTS = "STOP_LOADING_POSTS";
export const LOADING_POSTS_SUCCESS = "LOADING_POSTS_SUCCESS";
export const LOADING_POSTS_FAILURE = "LOADING_POSTS_FAILURE";