export const START_FETCHING_POSTS = "START_FETCHING_POSTS";
export const STOP_FETCHING_POSTS = "STOP_FETCHING_POSTS";
export const FETCHING_POSTS_SUCCESS = "FETCHING_POSTS_SUCCESS";
export const FETCHING_POSTS_FAILURE = "FETCHING_POSTS_FAILURE";