export const START_MODIFYING_POST = "START_MODIFYING_POST";
export const STOP_MODIFYING_POST = "STOP_MODIFYING_POST";
export const MODIFYING_POST_SUCCESS = "MODIFYING_POST_SUCCESS";
export const MODIFYING_POST_FAILURE = "MODIFYING_POST_FAILURE";
export const LOADING_ORIGINAL_POST_SUCCESS = "LOADING_ORIGINAL_POST_SUCCESS";
export const LOADING_ORIGINAL_POST_FAILURE = "LOADING_ORIGINAL_POST_FAILURE";
export const STOP_LOADING_ORIGINAL_POST = "STOP_LOADING_ORIGINAL_POST";
export const UPDATE_POST_TITLE = "UPDATE_POST_TITLE";
export const UPDATE_POST_CONTENT = "UPDATE_POST_CONTENT";

