export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL';