export const START_MODIFYING_COMMENT = "START_MODIFYING_COMMENT";
export const STOP_MODIFYING_COMMENT = "STOP_MODIFYING_COMMENT";
export const MODIFYING_COMMENT_SUCCESS = "MODIFYING_COMMENT_SUCCESS";
export const MODIFYING_COMMENT_FAILURE = "MODIFYING_COMMENT_FAILURE";
export const LOADING_ORIGINAL_COMMENT_SUCCESS = "LOADING_ORIGINAL_COMMENT_SUCCESS";
export const LOADING_ORIGINAL_COMMENT_FAILURE = "LOADING_ORIGINAL_COMMENT_FAILURE";
export const STOP_LOADING_ORIGINAL_COMMENT = "STOP_LOADING_ORIGINAL_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";