export const START_LOADING_SINGLE_POST = "START_LOADING_SINGLE_POST";
export const STOP_LOADING_SINGLE_POST = "STOP_LOADING_SINGLE_POST";
export const LOADING_SINGLE_POST_SUCCESS = "LOADING_SINGLE_POST_SUCCESS";
export const LOADING_SINGLE_POST_FAILURE = "LOADING_SINGLE_POST_FAILURE";
export const START_LOADING_COMMENTS = "START_LOADING_COMMENTS";
export const STOP_LOADING_COMMENTS = "STOP_LOADING_COMMENTS";
export const LOADING_COMMENTS_SUCCESS = "LOADING_COMMENTS_SUCCESS";
export const LOADING_COMMENTS_FAILURE = "LOADING_COMMENTS_FAILURE";
